{
  "id":21,
  "name":"childstutorial",
  "formtabs":[
    {
      "MIGX_id":1,
      "caption":"Resource",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":1,
          "field":"pagetitle",
          "caption":"Pagetitle",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":2,
          "field":"template",
          "caption":"Template",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"hidden",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":2
        },
        {
          "MIGX_id":3,
          "field":"show_in_tree",
          "caption":"Show in tree",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"listbox",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"no==||yes==1",
          "default":""
        }
      ]
    },
    {
      "MIGX_id":2,
      "caption":"Content",
      "print_before_tabs":"0",
      "fields":[
        {
          "MIGX_id":1,
          "field":"content",
          "caption":"Content",
          "description":"",
          "description_is_code":"0",
          "inputTV":"",
          "inputTVtype":"textarea",
          "configs":"",
          "sourceFrom":"config",
          "sources":"[]",
          "inputOptionValues":"",
          "default":""
        }
      ]
    },
    {
      "MIGX_id":3,
      "caption":"TVs",
      "fields":[
        {
          "MIGX_id":1,
          "field":"price",
          "caption":"Price",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":2,
          "field":"images",
          "caption":"Images",
          "inputTV":"images",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":3,
          "field":"categories",
          "caption":"Categories",
          "description":"",
          "inputTV":"",
          "inputTVtype":"listbox-multiple",
          "configs":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"---==||categoryA||categoryB||categoryC||categoryD",
          "default":""
        }
      ]
    }
  ],
  "contextmenus":"update||duplicate||recall_remove_delete||remove",
  "actionbuttons":"addItem||bulk||toggletrash||upload",
  "columnbuttons":"update||publish||unpublish",
  "filters":[
    {
      "MIGX_id":1,
      "name":"search",
      "label":"search",
      "emptytext":"search...",
      "type":"textbox",
      "getlistwhere":{
        "pagetitle:LIKE":"%[[+search]]%",
        "OR:longtitle:LIKE":"%[[+search]]%",
        "OR:content:LIKE":"%[[+search]]%"
      },
      "getcomboprocessor":"",
      "combotextfield":"",
      "comboidfield":"",
      "comboparent":""
    },
    {
      "MIGX_id":2,
      "name":"category",
      "label":"category",
      "emptytext":"- category filter -",
      "type":"combobox",
      "getlistwhere":"tvFilter::categories=inArray=[[+category]]",
      "getcomboprocessor":"getTVcombo",
      "combotextfield":"categories",
      "comboidfield":"",
      "comboparent":""
    }
  ],
  "extended":{
    "migx_add":"Add Childresource",
    "formcaption":"Child Resource",
    "update_win_title":"",
    "win_id":"childstutorial",
    "maxRecords":"",
    "addNewItemAt":"bottom",
    "multiple_formtabs":"",
    "extrahandlers":"this.handlePositionSelector||this.handleColumnSwitch",
    "packageName":"migxchildresources",
    "classname":"modResource",
    "task":"",
    "getlistsort":"menuindex",
    "getlistsortdir":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"",
    "has_jointable":"yes",
    "getlistwhere":"",
    "joins":[
      {
        "alias":"CreatedBy"
      }
    ],
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":"",
    "winbuttons":"",
    "onsubmitsuccess":"",
    "submitparams":""
  },
  "columns":[
    {
      "MIGX_id":1,
      "header":"ID",
      "dataIndex":"id",
      "width":10,
      "renderer":"",
      "sortable":true,
      "show_in_grid":1
    },
    {
      "MIGX_id":2,
      "header":"Pagetitle",
      "dataIndex":"pagetitle",
      "width":30,
      "renderer":"this.renderRowActions",
      "sortable":true,
      "show_in_grid":1
    },
    {
      "MIGX_id":3,
      "header":"Published",
      "dataIndex":"published",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderSwitchStatusOptions",
      "clickaction":"switchOption",
      "selectorconfig":"",
      "renderoptions":[
        {
          "MIGX_id":1,
          "name":"publish",
          "value":"0",
          "clickaction":"",
          "handler":"",
          "image":"assets\/components\/migx\/style\/images\/cross.png"
        },
        {
          "MIGX_id":2,
          "name":"unpublish",
          "value":1,
          "clickaction":"",
          "handler":"",
          "image":"assets\/components\/migx\/style\/images\/tick.png"
        }
      ]
    },
    {
      "MIGX_id":4,
      "header":"",
      "dataIndex":"deleted",
      "width":"",
      "renderer":"",
      "sortable":"false",
      "show_in_grid":"0"
    },
    {
      "MIGX_id":5,
      "header":"Price",
      "dataIndex":"price",
      "width":20,
      "renderer":"",
      "sortable":true,
      "show_in_grid":1
    },
    {
      "MIGX_id":6,
      "header":"Show in Tree",
      "dataIndex":"show_in_tree",
      "width":20,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"this.renderSwitchStatusOptions",
      "clickaction":"switchOption",
      "selectorconfig":"",
      "renderoptions":[
        {
          "MIGX_id":1,
          "name":"showintree",
          "value":"0",
          "clickaction":"",
          "handler":"",
          "image":"assets\/components\/migx\/style\/images\/cross.png"
        },
        {
          "MIGX_id":2,
          "name":"shownotintree",
          "value":1,
          "clickaction":"",
          "handler":"",
          "image":"assets\/components\/migx\/style\/images\/tick.png"
        }
      ]
    },
    {
      "MIGX_id":7,
      "header":"Created By",
      "dataIndex":"CreatedBy_username",
      "width":20,
      "renderer":"",
      "sortable":"false",
      "show_in_grid":1
    },
    {
      "MIGX_id":11,
      "header":"Menueindex",
      "dataIndex":"menuindex",
      "width":15,
      "sortable":true,
      "show_in_grid":1,
      "renderer":"this.renderPositionSelector",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    }
  ],
  "createdby":1,
  "createdon":"2012-07-29 19:12:13",
  "editedby":1,
  "editedon":"2014-01-22 08:03:39",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"2012-07-29 01:00:00",
  "publishedby":0
}